name: rip_college_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.3
  curved_navigation_bar: ^1.0.6
  google_fonts: ^6.2.1
  phosphor_flutter: ^2.1.0
  flutter_staggered_grid_view: ^0.7.0
  page_transition: ^2.2.1
  provider: ^6.1.2
  table_calendar: ^3.1.3
  carousel_slider: ^5.0.0
  animate_do: ^3.3.4
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_animate: ^4.5.2
  animations: ^2.0.11
  http: ^1.3.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/suiet/
    - assets/images/ihmt/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app-icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app-icon.png"

flutter_native_splash:
  color: "#ffffff"  # Background color for the splash screen
  image: "assets/icons/splash-logo.png"  # Path to your image (not GIF)
  android: true  # Enable splash on Android
  ios: true  # Enable splash on iOS
  web: false  # Optional: Disable splash on the web

